version: "3"

services:
  app:
    image: build-oncokb:latest
    ports:
      - "8080:8080"
    environment:
      - "JAVA_OPTS=-Djdbc.driverClassName=com.mysql.jdbc.Driver -Djdbc.url=jdbc:mysql://db:3306/oncokb?useUnicode=yes&characterEncoding=UTF-8&useSSL=false -Djdbc.username=root -Djdbc.password=rootdocker"
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=rootdocker
      - MYSQL_DATABASE=oncokb
    ports:
      - "3456:3306" # HOST_PORT:CONTAINER_PORT
    volumes:
      - ./core/src/main/resources/spring/database/database/oncokb.sql:/docker-entrypoint-initdb.d/oncokb.sql
